### ISSUE TITLE
Invalid file descriptor to ICU data received. error: process didn't exit successfully: `target\debug\cef.exe` (exit code: 0x80000003)

### ISSUE THREAD

**Issue by quocduongpy** [mycrl/webview-rs#3]
Hello
I tried running the above example but got the error:
`Invalid file descriptor to ICU data received. error: process didn't exit successfully: `target\debug\cef.exe` (exit code: 0x80000003)`

If you know how to fix it please help
Thanks a lot

**Comment by mycrl** [comment]
> Hello I tried running the above example but got the error: `Invalid file descriptor to ICU data received. error: process didn't exit successfully: `target\debug\cef.exe` (exit code: 0x80000003)`
> 
> If you know how to fix it please help Thanks a lot

cef needs some other resource files as well as dlls to run properly, this is something needed for chrome to run, due to the limitation of cargo, currently rust cargo can't handle the need to release resource files to target directory automatically, so you need to manually copy the resource files under the `build/webview-rs-xxx` directory to the target directory, although my project is a fork of my company's internal project, but in some ways it can't be easily used by others, this is also a limitation of cargo, if you need help, I can provide more information.

**Comment by quocduongpy** [comment]
@mycrl
Thank you very much
It worked <3
